# https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-error-message
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell
#
# https://docs.rubocop.org/en/stable/configuration/#severity

name: RuboCop

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: bundle init && bundle add --git=https://github.com/rubocop-hq/rubocop.git rubocop
      - run: rubocop --display-cop-names --extra-details --display-style-guide --parallel --format github .
